spring:
  datasource: 
    initialization-mode: always
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    password: Smanager@2020
    username: root
    url: jdbc:mysql://db:3306/smanager?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    url: jdbc:mysql://localhost:3306/smanager?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false    
    #url: jdbc:mysql://localhost:3306/smanager
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
        format_sql: true
        show_sql: true
