server:
  port: 8080
  
spring:
  application:
    name: 'compra'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka:8761/eureka